name: '✨ Feature Request'
description: Suggest new features or improvements
labels: [enhancement]
title: '[Feature] '

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please help us understand your idea.

  - type: dropdown
    id: feature_scope
    attributes:
      label: Is this for the template or generated projects?
      options:
        - Template (new options, generation features)
        - Generated Project (tooling, structure)
        - Both
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: |
        Describe the problem or use case this addresses...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you solve this problem?
      placeholder: |
        Describe your proposed solution...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches have you considered?
    validations:
      required: false

  - type: checkboxes
    id: breaking_change
    attributes:
      label: Would this be a breaking change?
      options:
        - label: This change would break existing functionality
          required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to help implement this feature?
      options:
        - label: I am willing to submit a PR for this feature
          required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information about this feature request
    validations:
      required: false
