name: '✨ Feature Request'
description: Suggest new features or improvements
labels: [enhancement]
title: '[Feature] '

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please help us understand your idea.

  - type: dropdown
    id: feature_scope
    attributes:
      label: Is this for the template or generated projects?
      options:
        - Template (new options, generation features)
        - Generated Project (tooling, structure)
        - Both
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: What feature would you like to see?
      placeholder: |
        A brief description of the feature you're requesting...
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Example
      description: How would this look to the end user?
      placeholder: |
        Show an example of how this would work or what the user would see/do...
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information about this feature request
    validations:
      required: false