name: '📦 Generated Project Bug Report'
description: Report a bug with the generated project (nox sessions, dependencies, tooling, structure)
labels: [bug, generated-project]
title: '[Generated Project Bug] '

body:
  - type: markdown
    attributes:
      value: |
        ## Generated Project Bug Report
        
        Report issues with **generated projects** including:
        - Nox session failures
        - Dependency or tooling problems
        - Build/packaging issues
        - Testing framework errors
        - Project configuration problems
        
        > **Note:** For issues with the **cookiecutter template itself** (generation process, template scripts), use the "Template Bug Report" template instead.

  - type: textarea
    id: description
    attributes:
      label: 📝 Bug Description
      description: Clearly describe the issue in your generated project
      placeholder: |
        Example: Running 'nox -s tests-python' fails with import errors...
    validations:
      required: true

  - type: dropdown
    id: issue_category
    attributes:
      label: 🏷️ Issue Category
      options:
        - Nox session failures
        - Dependency/package management
        - Build/packaging problems
        - Testing framework issues
        - Documentation build issues
        - Linting/formatting configuration
        - Type checking issues
        - Security scanning problems
        - CI/CD workflow issues
        - Rust extension issues
        - Container/Docker issues
        - Project structure/files
        - Other
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: 🔄 Steps to Reproduce
      description: Provide clear steps to reproduce the issue
      placeholder: |
        1. Generate project: cookiecutter gh:56kyle/cookiecutter-robust-python
        2. Select options: {project_name: "test", add_rust_extension: "no"}
        3. Run command: nox -s tests-python
        4. Error occurs: ...
      value: |
        1. 
        2. 
        3. 
        4. 
    validations:
      required: true

  - type: textarea
    id: cookiecutter_config
    attributes:
      label: ⚙️ Project Configuration
      description: Paste the contents of .cookiecutter.json from your generated project
      render: json
      placeholder: |
        {
          "project_name": "my-project",
          "add_rust_extension": "no",
          ...
        }
    validations:
      required: true

  - type: dropdown
    id: rust_extension
    attributes:
      label: 🦀 Rust Extension
      description: Does your project include Rust extensions?
      options:
        - "No"
        - "Yes"
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: 🖥️ Environment
      description: Please fill in your system information
      value: |
        - OS: 
        - Python version: 
        - uv version: 
        - nox version: 
        - Template version used: 
    validations:
      required: true

  - type: textarea
    id: command_output
    attributes:
      label: 💻 Command Output
      description: Paste the complete output of the failing command(s)
      render: shell
      placeholder: |
        Paste full command output here...
    validations:
      required: false

  - type: textarea
    id: workaround
    attributes:
      label: 🔧 Workaround
      description: If you found a temporary solution, please describe it
      placeholder: |
        Example: Manually editing pyproject.toml to fix the dependency version...
    validations:
      required: false