name: '📖 Documentation Issue'
description: Report documentation issues or suggest improvements
labels: [documentation]
title: '[Docs] '

body:
  - type: markdown
    attributes:
      value: |
        ## Documentation Issue
        
        Report problems or suggest improvements for:
        - Template documentation (README, docs/ folder)
        - Generated project documentation templates
        - Missing or unclear documentation
        - Documentation build issues
        - API/code documentation

  - type: dropdown
    id: doc_type
    attributes:
      label: 📁 Documentation Type
      options:
        - Template documentation (this repository)
        - Generated project documentation template
        - API/code documentation
        - Usage guides/tutorials
        - Configuration documentation
        - Troubleshooting guides
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 📝 Issue Description
      description: Describe the documentation problem and suggest improvements
      placeholder: |
        Example: The nox session documentation is missing examples for Rust projects...
    validations:
      required: true

  - type: input
    id: link
    attributes:
      label: 🔗 Documentation Link
      description: Link to the problematic documentation (if applicable)
      placeholder: https://cookiecutter-robust-python.readthedocs.io/en/latest/...
    validations:
      required: false

  - type: dropdown
    id: issue_type
    attributes:
      label: 🏷️ Issue Type
      options:
        - Missing documentation
        - Incorrect/outdated information
        - Unclear explanation
        - Documentation build failure
        - Broken links
        - Formatting issues
        - Suggestion for improvement
    validations:
      required: true

  - type: textarea
    id: suggested_improvement
    attributes:
      label: ✨ Suggested Improvement
      description: How can this documentation be improved? What would you like to see added or changed?
      placeholder: |
        Example: Add a section showing how to customize the nox configuration for different project types...
    validations:
      required: false
