name: '📦 Dependency Update'
description: Suggest updates to dependencies, tools, or versions
labels: [dependencies]
title: '[Dependency] '

body:
  - type: markdown
    attributes:
      value: |
        Suggest dependency or tooling updates.

  - type: input
    id: package
    attributes:
      label: Package/Tool Name
      description: What needs to be updated?
      placeholder: e.g., ruff, pytest, Python version
    validations:
      required: true

  - type: input
    id: current_version
    attributes:
      label: Current Version
      placeholder: e.g., 0.1.0, >=3.9
    validations:
      required: true

  - type: input
    id: proposed_version
    attributes:
      label: Proposed Version
      placeholder: e.g., 0.2.0, >=3.10
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: Update Reason
      description: Why should this be updated?
      placeholder: |
        Security fix, new features, performance improvements, etc.
    validations:
      required: true

  - type: checkboxes
    id: breaking_change
    attributes:
      label: Breaking Change
      options:
        - label: This update would introduce breaking changes
          required: false

  - type: checkboxes
    id: security
    attributes:
      label: Security Update
      options:
        - label: This is a security-related update
          required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any other relevant details (migration guide, testing needed, etc.)
    validations:
      required: false
