name: '🚀 Generated Project Feature Request'
description: Suggest improvements or new features for generated projects (nox sessions, tooling, structure)
labels: [enhancement, generated-project]
title: '[Generated Project Feature] '

body:
  - type: markdown
    attributes:
      value: |
        ## Generated Project Feature Request
        
        Suggest improvements for **generated projects** including:
        - New nox sessions
        - Tooling improvements
        - Dependency updates
        - Project structure enhancements
        - Development workflow improvements
        
        > **Note:** For improvements to the **cookiecutter template itself** (new template options, generation process), use the "Template Feature Request" template instead.

  - type: textarea
    id: problem
    attributes:
      label: 🎡 Problem or Use Case
      description: What problem would this feature solve for generated projects?
      placeholder: |
        Example: Generated projects need better support for async testing...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 💡 Proposed Solution
      description: Describe your proposed solution or feature in detail
      placeholder: |
        Example: Add pytest-asyncio to default dependencies and configure async test support...
    validations:
      required: true

  - type: dropdown
    id: feature_category
    attributes:
      label: 🏷️ Feature Category
      options:
        - New nox session
        - Dependency/tooling updates
        - Testing improvements
        - Build/packaging enhancements
        - Documentation improvements
        - Security enhancements
        - CI/CD workflow improvements
        - Development experience improvements
        - Rust extension features
        - Container/deployment features
        - Project structure improvements
        - Other
    validations:
      required: true

  - type: dropdown
    id: affects_rust
    attributes:
      label: 🦀 Rust Extension Impact
      description: Does this feature affect Rust extension projects?
      options:
        - "No - Python only"
        - "Yes - Rust extension projects"
        - "Both Python and Rust projects"
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: 🔧 Implementation Ideas
      description: How could this be implemented in the generated project template?
      placeholder: |
        Example: Modify pyproject.toml dependencies, add new nox session in noxfile.py...
    validations:
      required: false

  - type: textarea
    id: examples
    attributes:
      label: 🔗 Examples or References
      description: Links to similar implementations or examples from other projects
      placeholder: |
        Example: https://github.com/example/project implements this feature...
    validations:
      required: false

  - type: dropdown
    id: breaking_change
    attributes:
      label: ⚠️ Breaking Change Impact
      description: Would this change break existing generated projects or require migration?
      options:
        - "No - backward compatible"
        - "Yes - breaking change requiring migration"
        - "Only affects new projects"
        - "Unsure"
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: 📝 Additional Context
      description: Any other relevant information about this feature request
      placeholder: |
        Additional details, use cases, or considerations...
    validations:
      required: false